# Generated by Django 5.2 on 2025-04-18 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Tasks", "0003_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Group")),
                ("creater", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="creater_group", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="group_id",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="group", to="Tasks.group"),
        ),
    ]
