services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web-app:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./TaskFlow:/TaskFlow
    networks:
      - backend
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
volumes:
  postgres_data:

networks:
  backend:
    driver: bridge