target-version = "py312"
line-length = 70

indent-width = 4
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "manage.py",
]
extend-exclude = []
select = [
    "A",
    "ARG",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "I",
    "ICN",
    "INP",
    "M",
    "N",
    "PD",
    "PIE",
    "Q",
    "RUF",
    "SIM",
    "T",
    "TRY",
    "W",
    "YTT",
]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D202",
    "D203",
    "D212",
    "D400",
    "E501",
    "F401",
    "ANN101",
    "ANN102",
    "A002",
    "D106",
    "RUF012",
]
extend-select = []
extend-ignore = []

fix = true
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.flake8-bugbear]
extend-immutable-calls = ["datetime.datetime.now"]

[lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
avoid-escape = false

[lint.flake8-pytest-style]
fixture-parentheses = true



[lint.mccabe]
max-complexity = 10

[lint.isort]
force-single-line = false
split-on-trailing-comma = true
combine-as-imports = true
force-sort-within-sections = true
lines-between-types = 1
known-first-party = ["your_project_name"]
known-third-party = []
from-first = true

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[per-file-ignores]
"tests/*.py" = ["D100", "D101", "D103", "F401"]
"*/__init__.py" = ["F401"]
"src/my_module/exceptions.py" = ["D105"]

