# Generated by Django 5.2 on 2025-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
